// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBarSearch: typeof import('./src/@core/components/AppBarSearch.vue')['default']
    AppCardActions: typeof import('./src/@core/components/AppCardActions.vue')['default']
    AppCardCode: typeof import('./src/@core/components/AppCardCode.vue')['default']
    AppDateTimePicker: typeof import('./src/@core/app-form-elements/AppDateTimePicker.vue')['default']
    AppOtpInput: typeof import('./src/@core/components/AppOtpInput.vue')['default']
    AppSearchHeader: typeof import('./src/@core/components/AppSearchHeader.vue')['default']
    AppSelect: typeof import('./src/@core/app-form-elements/AppSelect.vue')['default']
    AppTextarea: typeof import('./src/@core/app-form-elements/AppTextarea.vue')['default']
    AppTextField: typeof import('./src/@core/app-form-elements/AppTextField.vue')['default']
    Calendar: typeof import('./src/@core/components/Calendar.vue')['default']
    CardAddEditDialog: typeof import('./src/@core/components/CardAddEditDialog.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    CardStatisticsVerticalSimple: typeof import('./src/@core/components/CardStatisticsVerticalSimple.vue')['default']
    ConfirmDialog: typeof import('./src/@core/components/ConfirmDialog.vue')['default']
    CustomizerSection: typeof import('./src/@core/components/CustomizerSection.vue')['default']
    DataTable: typeof import('./src/@core/components/DataTable.vue')['default']
    DialogCloseBtn: typeof import('./src/@core/components/DialogCloseBtn.vue')['default']
    EditAddressDialog: typeof import('./src/@core/components/EditAddressDialog.vue')['default']
    EnableOneTimePasswordDialog: typeof import('./src/@core/components/EnableOneTimePasswordDialog.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    I18n: typeof import('./src/@core/components/I18n.vue')['default']
    ImageUpload: typeof import('./src/@core/components/ImageUpload.vue')['default']
    ImageUploadMulti: typeof import('./src/@core/components/ImageUploadMulti.vue')['default']
    LoadingProvider: typeof import('./src/@core/components/Loading/LoadingProvider.vue')['default']
    MceEditor: typeof import('./src/@core/app-form-elements/MceEditor.vue')['default']
    Notifications: typeof import('./src/@core/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shortcuts: typeof import('./src/@core/components/Shortcuts.vue')['default']
    SnackbarProvider: typeof import('./src/@core/components/Snackbar/SnackbarProvider.vue')['default']
    TheCustomizer: typeof import('./src/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserInfoEditDialog: typeof import('./src/@core/components/UserInfoEditDialog.vue')['default']
    UserUpgradePlanDialog: typeof import('./src/@core/components/UserUpgradePlanDialog.vue')['default']
    VTreeNode: typeof import('./src/@core/components/TreeView/VTreeNode.vue')['default']
  }
}
